
//CLASES Y OBJETOS


const moto = {
    marca: '',
    nombre: '',
    modelo: '',
    cilindrada: '',
    compresion: '',
    valvulasporcilindro: '',
    llantaDelantera: '',
    llantaTrasera: '',
    distanciaEntreEjes: '',
    capacidadDeCombustible: '',
    hp: '',
    torque: '',
    velocidadMaxima: '',
    consumo: '',
    pesoEnSeco: '',
    altura: '',
    largo: '',
    ancho: '',
    alturaAlSuelo: '',

}


//CONEXION DE MI OBJETO CON LA API

function dato(valor) {
  return valor || "No disponible";
}

function mostrarFicha(tarjeta) {
  for (const clave in moto) {
    const elemento = tarjeta.querySelector("." + clave);
    if (elemento) {
      elemento.textContent = moto[clave];
    }
  }
}

function cargarMoto(modeloBuscado, tarjeta) {
  fetch("https://api.api-ninjas.com/v1/motorcycles?make=royal enfield&model=" + encodeURIComponent(modeloBuscado), {
    headers: { "X-Api-Key": "pn34mGlzRSAyfT3WpIuvO3MIvPGRSvjdo79vK5fJ" }
  })
    .then(function (respuesta) {
      return respuesta.json();
    })
    .then(function (motos) {
      if (motos.length === 0) {
        console.log("No se encontró ese modelo");
        return;
      }

      const datos = motos[0];
      console.log(datos);

      moto.marca = dato(datos.make);
      moto.modelo = dato(datos.model);
      moto.llantadelantera = dato(datos.front_tire);
      moto.llantatrasera = dato(datos.rear_tire);
      moto.cilindrada = dato(datos.displacement);
      moto.compresion = dato(datos.compression);
      moto.valvulasporcilindro = dato(datos.valves_per_cylinder);
      moto.distanciaentreejes = dato(datos.wheelbase);
      moto.capacidaddecombustible = dato(datos.fuel_capacity);
      moto.hp = dato(datos.power);
      moto.torque = dato(datos.torque);
      moto.velocidadmaxima = dato(datos.top_speed);
      moto.consumo = dato(datos.fuel_consumption);
      moto.pesoenseco = dato(datos.total_weight);
      moto.altura = dato(datos.total_height);
      moto.largo = dato(datos.total_length);
      moto.ancho = dato(datos.total_width);
      moto.alturaalsuelo = dato(datos.ground_clearance);
      moto.alturaalsillin = dato(datos.seat_height);

      mostrarFicha(tarjeta);
    })
    .catch(function (error) {
      console.log("Error:", error);
    });
}



document.querySelectorAll(".grid-motos article").forEach(function (tarjeta) {
  const foto = tarjeta.querySelector(".imgcua");
  const datos = tarjeta.querySelector(".datos");

  if (!datos) return;

  foto.addEventListener("click", function () {
    datos.classList.toggle("oculto");

    if (!datos.classList.contains("oculto")) {
      cargarMoto(tarjeta.getAttribute("data-modelo"), tarjeta);
    }
  });
});

//API DE ROYAL ENFIELD


[
  {
    "make": "Royal Enfield",
    "model": "Classic 350",
    "year": "2022",
    "type": "Classic",
    "displacement": "349.3 ccm (21.31 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "9.5:1",
    "bore_stroke": "72.0 x 85.8 mm (2.8 x 3.4 inches)",
    "valves_per_cylinder": "2",
    "fuel_system": "Carburettor. UCAL 29mm, Constant Vacuum Carburettor",
    "fuel_control": null,
    "lubrication": "Wet sump",
    "cooling": "Oil & air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Conventional Wet",
    "frame": "Twin Downtube Spine",
    "front_suspension": "Telescopic, 41mm forks",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin tube Emulsion shock absorbers with 6-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "100/90-19 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. ABS. 2-piston calipers ",
    "rear_brakes": "Single disc. ABS. Single Lead Internal Expanding",
    "seat_height": "805 mm (31.7 inches) If adjustable, lowest setting.",
    "ground_clearance": "170 mm (6.7 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.00 litres (3.43 US gallons)",
    "starter": "Electric & kick",
    "power": "19.7 HP (14.4  kW)) @ 6100 RPM",
    "torque": "27.0 Nm (2.8 kgf-m or 19.9 ft.lbs) @ 4000 RPM",
    "top_speed": "114.0 km/h (70.8 mph)",
    "fuel_consumption": "2.73 litres/100 km (36.6 km/l or 86.16 mpg)",
    "emission": "63.3 CO2 g/km. (CO2 - Carbon dioxide emission) ",
    "total_weight": "195.0 kg (429.9 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2145 mm (84.4 inches)",
    "SS": "785 mm (30.9 inches)",
    "ignition": "ECU",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Continental GT 650",
    "year": "2022",
    "type": "Classic",
    "displacement": "648.0 ccm (39.54 cubic inches)",
    "engine": "Twin, four-stroke",
    "compression": "9.5:1",
    "bore_stroke": "78.0 x 67.8 mm (3.1 x 2.7 inches)",
    "valves_per_cylinder": "4",
    "fuel_system": "Injection",
    "fuel_control": null,
    "lubrication": null,
    "cooling": "Air",
    "gearbox": "6-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet multi-plate",
    "frame": "Steel tubular, double cradle ",
    "front_suspension": "41 mm fork",
    "front_wheel_travel": "110 mm (4.3 inches)",
    "rear_suspension": "Single Coil - Over shocks",
    "rear_wheel_travel": "88 mm (3.5 inches)",
    "front_tire": "100/90-18 ",
    "rear_tire": "130/70-18 ",
    "front_brakes": "Single disc. ABS",
    "rear_brakes": "Single disc. ABS ",
    "seat_height": "820 mm (32.3 inches) If adjustable, lowest setting.",
    "ground_clearance": "174 mm (6.9 inches)",
    "wheelbase": "1398 mm (55.0 inches)",
    "fuel_capacity": "12.50 litres (3.30 US gallons)",
    "starter": "Electric",
    "power": "46.8 HP (34.2  kW)) @ 7150 RPM",
    "torque": "52.3 Nm (5.3 kgf-m or 38.6 ft.lbs) @ 5150 RPM",
    "top_speed": "164.0 km/h (101.9 mph)",
    "fuel_consumption": "4.20 litres/100 km (23.8 km/l or 56.00 mpg)",
    "emission": "97.4 CO2 g/km. (CO2 - Carbon dioxide emission) ",
    "total_weight": "212.0 kg (467.4 pounds)",
    "total_height": "1069 mm (42.1 inches)",
    "total_length": "2119 mm (83.4 inches)",
    "total_width": "820 mm (32.3 inches)",
    "ignition": "Digital spark ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Himalayan",
    "year": "2022",
    "type": "Enduro / offroad",
    "displacement": "411.0 ccm (25.08 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "9.5:1",
    "bore_stroke": "78.0 x 86.0 mm (3.1 x 3.4 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection",
    "fuel_control": "Single Overhead Cams (SOHC)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet, multi-plate",
    "frame": "Half-duplex split cradle ",
    "front_suspension": "Telescopic, 41 mm forks",
    "front_wheel_travel": "200 mm (7.9 inches)",
    "rear_suspension": "Monoshock with linkage",
    "rear_wheel_travel": "180 mm (7.1 inches)",
    "front_tire": "90/90-21 ",
    "rear_tire": "120/90-17 ",
    "front_brakes": "Single disc. Two-piston calipers. ABS.",
    "rear_brakes": "Single disc. Single-piston caliper. ABS.",
    "seat_height": "800 mm (31.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "220 mm (8.7 inches)",
    "wheelbase": "1465 mm (57.7 inches)",
    "fuel_capacity": "12.49 litres (3.30 US gallons)",
    "starter": "Electric",
    "power": "24.5 HP (17.9  kW)) @ 6500 RPM",
    "torque": "32.0 Nm (3.3 kgf-m or 23.6 ft.lbs) @ 4250 RPM",
    "top_speed": null,
    "fuel_consumption": "3.18 litres/100 km (31.4 km/l or 73.97 mpg)",
    "emission": "73.8 CO2 g/km. (CO2 - Carbon dioxide emission) ",
    "total_weight": "194.0 kg (427.7 pounds)",
    "total_height": "1360 mm (53.5 inches)",
    "total_length": "2190 mm (86.2 inches)",
    "total_width": "840 mm (33.1 inches)",
    "ignition": "ECU",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Interceptor 650",
    "year": "2022",
    "type": "Classic",
    "displacement": "648.0 ccm (39.54 cubic inches)",
    "engine": "Twin, four-stroke",
    "compression": "9.5:1",
    "bore_stroke": "78.0 x 67.8 mm (3.1 x 2.7 inches)",
    "valves_per_cylinder": "4",
    "fuel_system": "Injection",
    "fuel_control": null,
    "lubrication": null,
    "cooling": "Air",
    "gearbox": "6-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet multi-plate",
    "frame": "Steel tubular, double cradle ",
    "front_suspension": "41 mm fork",
    "front_wheel_travel": "110 mm (4.3 inches)",
    "rear_suspension": "Single Coil - Over shocks",
    "rear_wheel_travel": "88 mm (3.5 inches)",
    "front_tire": "100/90-18 ",
    "rear_tire": "130/70-18 ",
    "front_brakes": "Single disc. ABS",
    "rear_brakes": "Single disc. ABS ",
    "seat_height": "805 mm (31.7 inches) If adjustable, lowest setting.",
    "ground_clearance": "174 mm (6.9 inches)",
    "wheelbase": "1398 mm (55.0 inches)",
    "fuel_capacity": "13.70 litres (3.62 US gallons)",
    "starter": "Electric",
    "power": "46.8 HP (34.2  kW)) @ 7150 RPM",
    "torque": "52.3 Nm (5.3 kgf-m or 38.6 ft.lbs) @ 5150 RPM",
    "top_speed": "164.0 km/h (101.9 mph)",
    "fuel_consumption": "4.20 litres/100 km (23.8 km/l or 56.00 mpg)",
    "emission": "97.4 CO2 g/km. (CO2 - Carbon dioxide emission) ",
    "total_weight": "217.0 kg (478.4 pounds)",
    "total_height": "1120 mm (44.1 inches)",
    "total_length": "2119 mm (83.4 inches)",
    "total_width": "788 mm (31.0 inches)",
    "ignition": "Digital spark ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Meteor 350",
    "year": "2022",
    "type": "Classic",
    "displacement": "349.0 ccm (21.30 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "9.5:1",
    "bore_stroke": "72.0 x 85.8 mm (2.8 x 3.4 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection",
    "fuel_control": null,
    "lubrication": null,
    "cooling": "Oil & air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet Multiplate",
    "frame": "Twin Downtube Spine Frame",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": null,
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": null,
    "front_tire": "100/90-19 ",
    "rear_tire": "140/70-17 ",
    "front_brakes": "Single disc. ABS. Twin piston.",
    "rear_brakes": "Single disc. ABS",
    "seat_height": "765 mm (30.1 inches) If adjustable, lowest setting.",
    "ground_clearance": "170 mm (6.7 inches)",
    "wheelbase": "1400 mm (55.1 inches)",
    "fuel_capacity": "15.00 litres (3.96 US gallons)",
    "starter": "Electric",
    "power": "19.9 HP (14.5  kW)) @ 6100 RPM",
    "torque": "27.0 Nm (2.8 kgf-m or 19.9 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": "2.90 litres/100 km (34.5 km/l or 81.11 mpg)",
    "emission": "67.3 CO2 g/km. (CO2 - Carbon dioxide emission) ",
    "total_weight": "191.0 kg (421.1 pounds)",
    "total_height": "1140 mm (44.9 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "845 mm (33.3 inches)",
    "ignition": "ECU",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Bullet 350",
    "year": "2019",
    "type": "Classic",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": null,
    "fuel_control": null,
    "lubrication": null,
    "cooling": null,
    "gearbox": null,
    "transmission": null,
    "clutch": "Wet Multiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": null,
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": null,
    "front_tire": "90/90-19 ",
    "rear_tire": "110/80-18 ",
    "front_brakes": "Double disc",
    "rear_brakes": "Single disc",
    "seat_height": "805 mm (31.7 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1395 mm (54.9 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "185.0 kg (407.9 pounds)",
    "total_height": "1120 mm (44.1 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "810 mm (31.9 inches)",
    "ignition": null,
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Bullet 350 ES",
    "year": "2019",
    "type": "Classic",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": null,
    "fuel_control": null,
    "lubrication": null,
    "cooling": null,
    "gearbox": null,
    "transmission": null,
    "clutch": "Wet Multiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": null,
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": null,
    "front_tire": "90/90-19 ",
    "rear_tire": "110/80-18 ",
    "front_brakes": "Double disc",
    "rear_brakes": "Single disc",
    "seat_height": "805 mm (31.7 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1395 mm (54.9 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "189.0 kg (416.7 pounds)",
    "total_height": "1120 mm (44.1 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "810 mm (31.9 inches)",
    "ignition": null,
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Bullet Trials Work Replica 350",
    "year": "2019",
    "type": "Classic",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": null,
    "fuel_control": null,
    "lubrication": null,
    "cooling": null,
    "gearbox": null,
    "transmission": null,
    "clutch": "Wet Multiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": null,
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": null,
    "front_tire": "90/90-19 ",
    "rear_tire": "110/80-18 ",
    "front_brakes": "Double disc",
    "rear_brakes": "Single disc",
    "seat_height": "805 mm (31.7 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1390 mm (54.7 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "187.0 kg (412.3 pounds)",
    "total_height": "1123 mm (44.2 inches)",
    "total_length": "2080 mm (81.9 inches)",
    "total_width": "805 mm (31.7 inches)",
    "ignition": null,
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "500 T Bullet Trials",
    "year": "2019",
    "type": "Classic",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": null,
    "fuel_control": null,
    "lubrication": null,
    "cooling": "Air",
    "gearbox": null,
    "transmission": null,
    "clutch": null,
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork",
    "front_wheel_travel": null,
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": null,
    "front_tire": "90/90-19 ",
    "rear_tire": "110/80-18 ",
    "front_brakes": "Double disc",
    "rear_brakes": "Single disc",
    "seat_height": "800 mm (31.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "22.0 HP (16.1  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "192.0 kg (423.3 pounds)",
    "total_height": "1123 mm (44.2 inches)",
    "total_length": "2080 mm (81.9 inches)",
    "total_width": "805 mm (31.7 inches)",
    "ignition": "Digital",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Bullet 500",
    "year": "2019",
    "type": "Classic",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": null,
    "fuel_control": null,
    "lubrication": null,
    "cooling": "Air",
    "gearbox": null,
    "transmission": null,
    "clutch": "Wet Multiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork",
    "front_wheel_travel": null,
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": null,
    "front_tire": "90/90-19 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Double disc",
    "rear_brakes": "Single disc",
    "seat_height": "800 mm (31.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "22.0 HP (16.1  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "196.0 kg (432.1 pounds)",
    "total_height": "1110 mm (43.7 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "810 mm (31.9 inches)",
    "ignition": "Digital",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Bullet Trials Works Replica 500",
    "year": "2019",
    "type": "Classic",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Keihin",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "110/80-18 ",
    "front_brakes": "Single disc. 2-Piston caliper",
    "rear_brakes": "Single disc. Single-piston caliper",
    "seat_height": "800 mm (31.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "196.0 kg (432.1 pounds)",
    "total_height": "1123 mm (44.2 inches)",
    "total_length": "2080 mm (81.9 inches)",
    "total_width": "805 mm (31.7 inches)",
    "ignition": "Digital",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic 350 Gunmetal Grey",
    "year": "2019",
    "type": "Allround",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Carburettor. CV type",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic With Hydraulic Damping, 41 mm.",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Swing arm With Gas Shock Absorbers.",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "110/90-18 ",
    "front_brakes": "Single disc. Two piston caliper",
    "rear_brakes": "Single disc. Single piston caliper",
    "seat_height": "775 mm (30.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1390 mm (54.7 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": "120.0 km/h (74.6 mph)",
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "194.0 kg (427.7 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2160 mm (85.0 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "TCI",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic 350 Redditch",
    "year": "2019",
    "type": "Allround",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Carburettor. CV type",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic With Hydraulic Damping, 41 mm.",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Swing arm With Gas Shock Absorbers.",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "110/90-18 ",
    "front_brakes": "Single disc. Two piston caliper",
    "rear_brakes": "Single disc. Single piston caliper",
    "seat_height": "775 mm (30.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1390 mm (54.7 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": "120.0 km/h (74.6 mph)",
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "194.0 kg (427.7 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2160 mm (85.0 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "TCI",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic 350 Signals",
    "year": "2019",
    "type": "Classic",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Carburettor. UCAL 29mm, Constant Vacuum Carburettor",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic, 35mm forks",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Swing Arm With Gas Shock Absorbers",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "110/90-18 ",
    "front_brakes": "Single disc. 2-piston calipers",
    "rear_brakes": "Single disc. Single Lead Internal Expanding",
    "seat_height": null,
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1390 mm (54.7 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "194.0 kg (427.7 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2160 mm (85.0 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "Transistorised Coil Ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic 500",
    "year": "2019",
    "type": "Allround",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Keihin",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "110/90-18 ",
    "front_brakes": "Single disc. 2-Piston caliper",
    "rear_brakes": "Single disc. Single-piston caliper",
    "seat_height": null,
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "196.0 kg (432.1 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "Digital",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic 500 Pegasus",
    "year": "2019",
    "type": "Classic",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Keihin",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-18 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. 2-Piston caliper",
    "rear_brakes": "Single disc. Single-piston caliper",
    "seat_height": null,
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1360 mm (53.5 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "194.0 kg (427.7 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "Digital",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic 500 Squadron Blue",
    "year": "2019",
    "type": "Classic",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Keihin",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-18 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. 2-Piston caliper",
    "rear_brakes": "Single disc. Single-piston caliper",
    "seat_height": null,
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "196.0 kg (432.1 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "Digital",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic 500 Stealth Black",
    "year": "2019",
    "type": "Classic",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Keihin",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-18 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. 2-Piston caliper",
    "rear_brakes": "Single disc. Single-piston caliper",
    "seat_height": null,
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "196.0 kg (432.1 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "Digital",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic Chrome 500",
    "year": "2019",
    "type": "Allround",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Digital Electronic Ignition",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Mulitiplate in oil",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic, hydraulic damping",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Swing arm with adjustable Gas filled shock absorber",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. Twin piston",
    "rear_brakes": "Single disc",
    "seat_height": "790 mm (31.1 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "187.0 kg (412.3 pounds)",
    "total_height": "1050 mm (41.3 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": null,
    "ignition": "Electronic",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Classic Desert Storm",
    "year": "2019",
    "type": "Allround",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Keihin EFI",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. 2-Piston caliper",
    "rear_brakes": "Expanding brake (drum brake)",
    "seat_height": null,
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1380 mm (54.3 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "196.0 kg (432.1 pounds)",
    "total_height": "1050 mm (41.3 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "Digital",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Concept KX",
    "year": "2019",
    "type": "Sport",
    "displacement": "838.0 ccm (51.13 cubic inches)",
    "engine": "V2, two-stroke",
    "compression": null,
    "bore_stroke": "80.0 x 83.8 mm (3.1 x 3.3 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": null,
    "cooling": null,
    "gearbox": null,
    "transmission": "Chain   (final drive)",
    "clutch": null,
    "frame": null,
    "front_suspension": "Girder Fork, Single Damper",
    "front_wheel_travel": null,
    "rear_suspension": "Single Damper with Progressive Link",
    "rear_wheel_travel": null,
    "front_tire": null,
    "rear_tire": null,
    "front_brakes": "Double disc. ABS",
    "rear_brakes": "Single disc. ABS",
    "seat_height": "760 mm (29.9 inches) If adjustable, lowest setting.",
    "ground_clearance": "128 mm (5.0 inches)",
    "wheelbase": "1530 mm (60.2 inches)",
    "fuel_capacity": null,
    "starter": null,
    "power": "90.0 HP (65.7  kW))",
    "torque": null,
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": null,
    "total_height": "998 mm (39.3 inches)",
    "total_length": "2160 mm (85.0 inches)",
    "total_width": "778 mm (30.6 inches)",
    "ignition": null,
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Continental GT 650",
    "year": "2019",
    "type": "Allround",
    "displacement": "648.0 ccm (39.54 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "9.5:1",
    "bore_stroke": "87.0 x 90.0 mm (3.4 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection",
    "fuel_control": "Single Overhead Cams (SOHC)",
    "lubrication": "Wet sump",
    "cooling": "Oil & air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet, multi-plate",
    "frame": "Twin downtube cradle ",
    "front_suspension": "Telescopic, 41mm forks",
    "front_wheel_travel": "110 mm (4.3 inches)",
    "rear_suspension": "Twin coil-over shocks",
    "rear_wheel_travel": "88 mm (3.5 inches)",
    "front_tire": "100/90-18 ",
    "rear_tire": "130/70-18 ",
    "front_brakes": "Single disc. Floating discs. Brembo 2-piston floating caliper.",
    "rear_brakes": "Single disc. Floating disc. Single-piston caliper. ",
    "seat_height": "793 mm (31.2 inches) If adjustable, lowest setting.",
    "ground_clearance": "174 mm (6.9 inches)",
    "wheelbase": "1398 mm (55.0 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "47.0 HP (34.3  kW)) @ 7250 RPM",
    "torque": "52.0 Nm (5.3 kgf-m or 38.4 ft.lbs) @ 5250 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": null,
    "total_height": "1024 mm (40.3 inches)",
    "total_length": "2122 mm (83.5 inches)",
    "total_width": "744 mm (29.3 inches)",
    "ignition": "Digital Electronic Ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Himalayan",
    "year": "2019",
    "type": "Enduro / offroad",
    "displacement": "411.0 ccm (25.08 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "9.5:1",
    "bore_stroke": "78.0 x 86.0 mm (3.1 x 3.4 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection",
    "fuel_control": "Single Overhead Cams (SOHC)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet, multi-plate",
    "frame": "Half-duplex split cradle frame",
    "front_suspension": "Telescopic, 41 mm forks",
    "front_wheel_travel": "200 mm (7.9 inches)",
    "rear_suspension": "Monoshock with linkage",
    "rear_wheel_travel": "180 mm (7.1 inches)",
    "front_tire": "90/90-21 ",
    "rear_tire": "120/90-17 ",
    "front_brakes": "Single disc. Two-piston calipers. ",
    "rear_brakes": "Single disc. Single-piston caliper. ",
    "seat_height": "800 mm (31.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "220 mm (8.7 inches)",
    "wheelbase": "1465 mm (57.7 inches)",
    "fuel_capacity": "15.00 litres (3.96 US gallons)",
    "starter": "Electric & kick",
    "power": "24.5 HP (17.9  kW)) @ 6500 RPM",
    "torque": "32.0 Nm (3.3 kgf-m or 23.6 ft.lbs) @ 4250 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "194.0 kg (427.7 pounds)",
    "total_height": "1360 mm (53.5 inches)",
    "total_length": "2190 mm (86.2 inches)",
    "total_width": "840 mm (33.1 inches)",
    "ignition": "Digital electronic ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Interceptor 650",
    "year": "2019",
    "type": "Allround",
    "displacement": "648.0 ccm (39.54 cubic inches)",
    "engine": "Twin, four-stroke",
    "compression": "9.5:1",
    "bore_stroke": "78.0 x 67.8 mm (3.1 x 2.7 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection",
    "fuel_control": null,
    "lubrication": null,
    "cooling": "Air",
    "gearbox": "6-speed",
    "transmission": "Chain   (final drive)",
    "clutch": null,
    "frame": "Steel tubular, double cradle frame",
    "front_suspension": "41 mm front fork",
    "front_wheel_travel": "110 mm (4.3 inches)",
    "rear_suspension": "Twin coil-over shocks",
    "rear_wheel_travel": "88 mm (3.5 inches)",
    "front_tire": "100/90-18 ",
    "rear_tire": "130/70-18 ",
    "front_brakes": "Single disc. ABS",
    "rear_brakes": "Single disc. ABS ",
    "seat_height": "804 mm (31.7 inches) If adjustable, lowest setting.",
    "ground_clearance": "174 mm (6.9 inches)",
    "wheelbase": null,
    "fuel_capacity": "13.70 litres (3.62 US gallons)",
    "starter": "Electric",
    "power": "47.0 HP (34.3  kW)) @ 7100 RPM",
    "torque": "52.0 Nm (5.3 kgf-m or 38.4 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "202.0 kg (445.3 pounds)",
    "total_height": "1165 mm (45.9 inches)",
    "total_length": "2122 mm (83.5 inches)",
    "total_width": "789 mm (31.1 inches)",
    "ignition": "Digital spark ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Thunderbird X350",
    "year": "2019",
    "type": "Classic",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "7.3:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Carburettor. CV type",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic With Hydraulic Damping, 41 mm.",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Swing arm With Gas Shock Absorbers.",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "120/80-19 ",
    "front_brakes": "Single disc. Two piston caliper",
    "rear_brakes": "Single disc. Single piston caliper",
    "seat_height": "775 mm (30.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1350 mm (53.1 inches)",
    "fuel_capacity": "20.00 litres (5.28 US gallons)",
    "starter": "Electric & kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": "120.0 km/h (74.6 mph)",
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "197.0 kg (434.3 pounds)",
    "total_height": "1140 mm (44.9 inches)",
    "total_length": "2060 mm (81.1 inches)",
    "total_width": "830 mm (32.7 inches)",
    "ignition": "TCI",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Thunderbird 350",
    "year": "2019",
    "type": "Classic",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "7.3:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Carburettor. CV type",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic With Hydraulic Damping, 41 mm.",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Swing arm With Gas Shock Absorbers.",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. Two piston caliper",
    "rear_brakes": "Single disc. Single piston caliper",
    "seat_height": "775 mm (30.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1350 mm (53.1 inches)",
    "fuel_capacity": "20.00 litres (5.28 US gallons)",
    "starter": "Electric & kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": "120.0 km/h (74.6 mph)",
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "197.0 kg (434.3 pounds)",
    "total_height": "1205 mm (47.4 inches)",
    "total_length": "2060 mm (81.1 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "TCI",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Thunderbird 500",
    "year": "2019",
    "type": "Allround",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Digital",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. 2-piston calipers",
    "rear_brakes": "Single disc. Single-piston",
    "seat_height": "775 mm (30.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1350 mm (53.1 inches)",
    "fuel_capacity": "20.00 litres (5.28 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "199.0 kg (438.7 pounds)",
    "total_height": "1205 mm (47.4 inches)",
    "total_length": "2060 mm (81.1 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "Digital electronic ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Thunderbird X 500",
    "year": "2019",
    "type": "Classic",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Injection. Digital",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet mulitiplate",
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. Ventilated disc, 2-piston calipers",
    "rear_brakes": "Single disc. Single-piston",
    "seat_height": "775 mm (30.5 inches) If adjustable, lowest setting.",
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1350 mm (53.1 inches)",
    "fuel_capacity": "20.00 litres (5.28 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "199.0 kg (438.7 pounds)",
    "total_height": "1140 mm (44.9 inches)",
    "total_length": "2040 mm (80.3 inches)",
    "total_width": "830 mm (32.7 inches)",
    "ignition": "Digital electronic ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Bullet 350",
    "year": "2018",
    "type": "Classic",
    "displacement": "346.0 ccm (21.11 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "70.0 x 90.0 mm (2.8 x 3.5 inches)",
    "valves_per_cylinder": null,
    "fuel_system": "Carburettor. UCAL 29mm, Constant Vacuum Carburettor",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": null,
    "frame": "Single downtube, using engine as stressed member",
    "front_suspension": "Telescopic fork, 35 mm",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "3.25-19 ",
    "rear_tire": "3.25-19 ",
    "front_brakes": "Expanding brake (drum brake). Twin drum",
    "rear_brakes": "Expanding brake (drum brake)",
    "seat_height": null,
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1370 mm (53.9 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Kick",
    "power": "19.8 HP (14.5  kW)) @ 5250 RPM",
    "torque": "28.0 Nm (2.9 kgf-m or 20.7 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "183.0 kg (403.4 pounds)",
    "total_height": "1030 mm (40.6 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "810 mm (31.9 inches)",
    "ignition": "Transistorised Coil Ignition",
    "dry_weight": null
  },
  {
    "make": "Royal Enfield",
    "model": "Bullet 500",
    "year": "2018",
    "type": "Classic",
    "displacement": "499.0 ccm (30.45 cubic inches)",
    "engine": "Single cylinder, four-stroke",
    "compression": "8.5:1",
    "bore_stroke": "84.0 x 90.0 mm (3.3 x 3.5 inches)",
    "valves_per_cylinder": "2",
    "fuel_system": "Injection",
    "fuel_control": "Overhead Valves (OHV)",
    "lubrication": "Wet sump",
    "cooling": "Air",
    "gearbox": "5-speed",
    "transmission": "Chain   (final drive)",
    "clutch": "Wet, manual multiple discs",
    "frame": "Single downtube",
    "front_suspension": "Telescopic fork, 35mm",
    "front_wheel_travel": "130 mm (5.1 inches)",
    "rear_suspension": "Twin gas charged shock absorbers with 5-step adjustable preload",
    "rear_wheel_travel": "80 mm (3.1 inches)",
    "front_tire": "90/90-19 ",
    "rear_tire": "120/80-18 ",
    "front_brakes": "Single disc. 2-piston calipers",
    "rear_brakes": "Expanding brake (drum brake)",
    "seat_height": null,
    "ground_clearance": "135 mm (5.3 inches)",
    "wheelbase": "1360 mm (53.5 inches)",
    "fuel_capacity": "13.50 litres (3.57 US gallons)",
    "starter": "Electric & kick",
    "power": "27.2 HP (19.9  kW)) @ 5250 RPM",
    "torque": "41.3 Nm (4.2 kgf-m or 30.5 ft.lbs) @ 4000 RPM",
    "top_speed": null,
    "fuel_consumption": null,
    "emission": null,
    "total_weight": "194.0 kg (427.7 pounds)",
    "total_height": "1090 mm (42.9 inches)",
    "total_length": "2140 mm (84.3 inches)",
    "total_width": "790 mm (31.1 inches)",
    "ignition": "Digital electronic ignition",
    "dry_weight": null
  }
]